# Generated by Django 2.2.1 on 2019-05-21 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('example', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Example model',
            },
        ),
    ]
